# Generated by Django 3.1.3 on 2021-02-25 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.BigIntegerField(default=-1)),
                ('modified_by', models.BigIntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=200)),
                ('is_editable', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
