# Generated by Django 3.1.3 on 2021-01-30 10:45

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import root.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.BigIntegerField(default=-1)),
                ('modified_by', models.BigIntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'root_black_list',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.BigIntegerField(default=-1)),
                ('modified_by', models.BigIntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fa_name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'root_city',
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.BigIntegerField(default=-1)),
                ('modified_by', models.BigIntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'root_following',
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.BigIntegerField(default=-1)),
                ('modified_by', models.BigIntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.CharField(default=root.models.generate_decimal_uid, max_length=4, unique=True)),
                ('name', models.CharField(default='', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'root_job_category',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.BigIntegerField(default=-1)),
                ('modified_by', models.BigIntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.IntegerField()),
                ('expire', models.BigIntegerField()),
                ('try_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'root_otp',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.BigIntegerField(default=-1)),
                ('modified_by', models.BigIntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('fa_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'root_province',
            },
        ),
        migrations.CreateModel(
            name='SalesMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.BigIntegerField(default=-1)),
                ('modified_by', models.BigIntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('job_category_description', models.CharField(blank=True, max_length=50, null=True)),
                ('uid', models.CharField(max_length=18)),
                ('full_name', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(blank=True, max_length=20, null=True)),
                ('store_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(max_length=200)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('working_days', models.CharField(max_length=27)),
                ('activity_type', models.CharField(choices=[('ON', 'Online'), ('OFF', 'Offline'), ('ALL', 'All')], max_length=3)),
                ('is_private', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'root_sales_man',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('modified_at', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('created_by', models.BigIntegerField(default=-1)),
                ('modified_by', models.BigIntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('uid', models.CharField(default=root.models.generate_hex_uid, max_length=8, unique=True)),
                ('mobile', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^09\\d{9}$')])),
                ('nick_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('score', models.IntegerField(default=100)),
                ('picture', models.BinaryField(null=True, validators=[django.core.validators.validate_image_file_extension])),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'root_user',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('mobile', 'deleted_date'), name='deleted_user'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='root.city'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='job_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='root.jobcategory'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.user'),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.user'),
        ),
        migrations.AddField(
            model_name='following',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to='root.user'),
        ),
        migrations.AddField(
            model_name='following',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.user'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='root.province'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='banned_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_user', to='root.user'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.user'),
        ),
        migrations.AddConstraint(
            model_name='salesman',
            constraint=models.UniqueConstraint(fields=('unique', 'uid', 'deleted_date'), name='deleted_salesman'),
        ),
    ]
