# Generated by Django 3.1.3 on 2020-11-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(null=True),
        ),
    ]
