# Generated by Django 3.1.3 on 2021-01-09 07:20

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted_uid',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(default=main_app.models.uid_generator, max_length=8),
        ),
    ]
