# Generated by Django 3.1.3 on 2020-12-01 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^(\\+98|0)?9\\d{9}$]')]),
        ),
    ]
