# Generated by Django 3.1.3 on 2020-12-01 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201201_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('(\\+98|0)?9\\d{9}]')]),
        ),
    ]
