# Generated by Django 3.1.3 on 2020-12-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201201_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
