# Generated by Django 3.1.3 on 2021-01-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210109_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_deleted_uid',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_date',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
