# Generated by Django 3.1.3 on 2021-01-15 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210114_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nick_name',
            field=models.CharField(default='hey', max_length=50),
            preserve_default=False,
        ),
    ]
